### ISSUE TITLE
Handling WindPlotter KeyError on 'Time'

### ISSUE THREAD

**Issue by MiCurry** [seacast/SharkEyes#108]
The NAM's model references u-component_of_wind_height_above_ground and v-component_of_wind_height_above_ground with different 'time' variables (ie reftime1, reftime2, time etc). which causes seacast to not be able to pull the amount of times for the datafile.

This can probably be fixed by pulling the coordinate from the u and v component fields and using that to grab the times.

**Comment by MiCurry** [comment]
Here's the line: https://github.com/seacast/SharkEyes/blob/master/pl_plot/plot_functions.py#L531

**Comment by Bastion-** [comment]
I added a check for which variable the wind model is using. I updated plotter, plot functions, and manage.py with the new check. I tested it and it works.
