### ISSUE TITLE
Datafile.delete() only deletes datafiles within settings.NETCDF_SORAGE_DIR

### ISSUE THREAD

**Issue by MiCurry** [seacast/SharkEyes#114]
Datafile.delete() only deletes datafiles within settings.NETCDF_SORAGE_DIR and not any datafiles located elsewhere.

**Comment by MiCurry** [comment]
A bigger fix would be to have each datafile entry store its datafile's location.

**Comment by Bastion-** [comment]
I added the paths for the wave and wind directories to the function. This should solve the issue without requiring any significant retooling.
